# Generated by Django 5.2.7 on 2025-11-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('preferredname', models.CharField(blank=True, max_length=100, null=True)),
                ('homephone', models.CharField(blank=True, max_length=20, null=True)),
                ('workphone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobilephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('postaladdress', models.CharField(blank=True, max_length=100, null=True)),
                ('medicarenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('medicarelineno', models.CharField(blank=True, max_length=100, null=True)),
                ('medicareexpiry', models.CharField(blank=True, max_length=7, null=True)),
                ('postalcity', models.CharField(blank=True, max_length=100, null=True)),
                ('postalpostcode', models.CharField(blank=True, max_length=100, null=True)),
                ('pensioncode', models.CharField(blank=True, max_length=100, null=True)),
                ('pensionno', models.CharField(blank=True, max_length=100, null=True)),
                ('pensionexpiry', models.CharField(blank=True, max_length=100, null=True)),
                ('dvacode', models.CharField(blank=True, max_length=100, null=True)),
                ('dvanumber', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
